import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Bot, ChevronRight, LoaderCircle, Send, Sparkles, Trash2 } from 'lucide-react'
import TravelerTabs from '../../../components/TravelerTabs/TravelerTabs'
import { generateTravelerPlan } from '../../../services/travelerPortalService'

const examples = ['Weekend foodie trip in Cebu', 'Family-friendly island experiences', 'Affordable cultural activities', 'Top-rated Cebu adventures']
export default function AIPlanner() {
  const navigate = useNavigate(); const [messages, setMessages] = useState([]); const [input, setInput] = useState(''); const [itinerary, setItinerary] = useState([]); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [activeView, setActiveView] = useState('chat')
  const send = async () => { const prompt = input.trim(); if (!prompt) return; const next = [...messages, { role: 'user', text: prompt }]; setMessages(next); setInput(''); setLoading(true); setError(''); try { const plan = await generateTravelerPlan(prompt); setItinerary(plan.itinerary); setMessages([...next, { role: 'ai', text: plan.reply }]) } catch (e) { setError(e.message) } finally { setLoading(false) } }
  const total = itinerary.reduce((sum, item) => sum + Number(item.price || 0), 0)
  return <main className="portal-page traveler-dashboard-page"><div className="container planner-shell"><div className="planner-mobile-tabs"><button className={`planner-tab ${activeView === 'chat' ? 'active' : ''}`} onClick={() => setActiveView('chat')}>Chat</button><button className={`planner-tab ${activeView === 'canvas' ? 'active' : ''}`} onClick={() => setActiveView('canvas')}>Itinerary</button></div>
    <section className={`planner-pane planner-chat-pane ${activeView === 'chat' ? 'is-active' : ''}`}><div className="planner-pane-header"><div><p className="eyebrow">Database itinerary planner</p><h2>Plan your next trip</h2></div><div className="planner-badge"><Bot size={16} /> Live catalog</div></div><div className="planner-message-list">{messages.length === 0 && !loading && <div className="planner-empty-state"><h3>Start with a few details</h3><p>The planner matches published GuideVerse experiences.</p><div className="planner-example-prompts">{examples.map(prompt => <button key={prompt} className="planner-example-prompt" onClick={() => setInput(prompt)}>{prompt}</button>)}</div></div>}{messages.map((message, index) => <div key={index} className={`bubble ${message.role === 'user' ? 'user-message' : 'ai-message'}`}>{message.text}</div>)}{loading && <div className="bubble ai-message"><LoaderCircle className="spinner" /> Matching live experiences…</div>}{error && <div className="inline-banner">{error}</div>}</div><div className="planner-input-panel"><textarea className="conversational-input" value={input} onChange={event => setInput(event.target.value)} onKeyDown={event => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); send() } }} placeholder="Try: 3 days in Cebu, love food and beaches" maxLength={500} /><div className="planner-input-meta"><span>{input.length}/500</span><button className="btn btn-primary planner-send-btn" disabled={!input.trim() || loading} onClick={send}><Send size={16} /> Send</button></div></div></section>
    <section className={`planner-pane planner-canvas-pane ${activeView === 'canvas' ? 'is-active' : ''}`}><div className="planner-pane-header"><div><p className="eyebrow">Saved recommendation</p><h2>Live day-by-day matches</h2></div></div>{itinerary.length === 0 ? <div className="planner-empty-canvas"><Sparkles size={20} /><h3>No plan yet</h3><p>Your database-matched itinerary will appear here.</p></div> : <><div className="planner-itinerary-list">{itinerary.map(slot => <article key={slot.day} className="portal-card card planner-itinerary-day"><div className="planner-itinerary-day-header"><div><p className="eyebrow">Day {slot.day}</p><h3>{slot.title}</h3></div><button className="planner-delete-btn" onClick={() => setItinerary(items => items.filter(item => item.day !== slot.day))}><Trash2 size={15} /></button></div><button className="planner-provider-slot" onClick={() => navigate(`/experience/${slot.experienceId}`)}><div><strong>{slot.provider}</strong><p>{slot.note}</p></div><div className="planner-provider-slot-meta"><span>{slot.currency} {Number(slot.price).toFixed(2)}</span><ChevronRight size={16} /></div></button></article>)}</div><p className="planner-bundle-total">Catalog total: {itinerary[0]?.currency} {total.toFixed(2)}</p></>}</section>
  </div><TravelerTabs /></main>
}
