const API_BASE_URL=(import.meta.env.VITE_API_BASE_URL||'').replace(/\/$/,'')
import { providerAuthHeaders } from './providerAuth'
const headers=()=>({Accept:'application/json',...providerAuthHeaders()})
async function request(path,options={}){const response=await fetch(`${API_BASE_URL}${path}`,{...options,headers:{...headers(),...options.headers}});if(response.status===204)return null;const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(typeof body.detail==='string'?body.detail:'Provider operation failed');return body}
const json=(method,body)=>({method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})
export const getProviderDashboard=()=>request('/api/provider/dashboard')
export const getProviderBookings=()=>request('/api/provider/bookings')
export const getProviderBooking=bookingId=>request(`/api/provider/bookings/${encodeURIComponent(bookingId)}`)
export const setInstantAvailability=value=>request('/api/provider/instant-availability',json('PUT',{is_available_now:value}))
export const getProviderCalendar=(start,end)=>request(`/api/provider/calendar?start=${start}&end=${end}`)
export const saveProviderAvailability=payload=>request('/api/provider/calendar',json('PUT',payload))
export const getProviderBids=()=>request('/api/provider/bids')
export const submitProviderBid=(id,payload)=>request(`/api/provider/bids/${id}`,json('POST',payload))
export const getProviderProposalRoom=bidId=>request(`/api/provider/bids/${bidId}/room`)
export const sendProviderProposalMessage=(bidId,body)=>request(`/api/provider/bids/${bidId}/messages`,json('POST',{body}))
export const updateProviderBid=(bidId,payload)=>request(`/api/provider/bids/${bidId}`,json('PUT',payload))
export const getProviderConversations=()=>request('/api/provider/conversations')
export const sendProviderMessage=(id,body)=>request(`/api/provider/conversations/${id}/messages`,json('POST',{body}))
export const getProviderEarnings=(start,end)=>request(`/api/provider/earnings?start=${start}&end=${end}`)
export const savePayoutSchedule=value=>request('/api/provider/payout-settings',json('PUT',{payout_schedule:value}))
