import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { FileText, MessageCircle, Search } from 'lucide-react'
import TravelerTabs from '../../../components/TravelerTabs/TravelerTabs'
import { getTravelerTrips } from '../../../services/travelerPortalService'

const tabs = ['upcoming', 'in-progress', 'completed', 'cancelled']
export default function TripsHub() {
  const navigate = useNavigate(); const [active, setActive] = useState('upcoming'); const [trips, setTrips] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  useEffect(() => { getTravelerTrips().then(setTrips).catch(e => setError(e.message)).finally(() => setLoading(false)) }, [])
  const now = Date.now(); const category = trip => trip.status === 'cancelled' ? 'cancelled' : trip.status === 'completed' || new Date(trip.end_time).getTime() < now ? 'completed' : new Date(trip.start_time).getTime() <= now ? 'in-progress' : 'upcoming'; const filtered = trips.filter(trip => category(trip) === active)
  return <main className="portal-page trips-hub-page"><div className="container trips-hub-shell"><header className="trips-hub-header"><div><p className="eyebrow">Traveler hub</p><h1>My Trips</h1></div></header><div className="status-tabs">{tabs.map(tab => <button key={tab} className={`status-tab ${active === tab ? 'active' : ''}`} onClick={() => setActive(tab)}>{tab.replace('-', ' ')}</button>)}</div>{error && <div className="inline-banner">{error}</div>}{loading ? <div className="trips-grid"><div className="trip-skeleton-card" /></div> : filtered.length ? <div className="trips-grid">{filtered.map(trip => <article key={trip.id} className="portal-card card trip-summary-card" onClick={() => navigate(`/app/traveler/trips/${trip.id}`)}><div className="trip-summary-top"><div><h3>{trip.title}</h3><p>{new Date(trip.start_time).toLocaleString()}</p></div><span className="trip-badge">{trip.status}</span></div><div className="trip-summary-meta"><span>Provider</span><strong>{trip.provider}</strong></div><div className="trip-summary-actions"><button className="btn btn-primary btn-sm" onClick={event => { event.stopPropagation(); navigate(`/app/traveler/bookings/${trip.id}/confirmation`) }}><FileText size={14} /> View ticket</button>{trip.conversation_id && <button className="btn btn-outline btn-sm" onClick={event => { event.stopPropagation(); navigate(`/app/traveler/messages?conversation=${trip.conversation_id}`) }}><MessageCircle size={14} /> Message Guide</button>}</div></article>)}</div> : <div className="trips-empty-state"><h3>No {active} trips</h3><button className="btn btn-primary" onClick={() => navigate('/search')}><Search size={16} /> Explore experiences</button></div>}</div><TravelerTabs /></main>
}
