import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Clock, Compass, MessageCircle, Sparkles, Zap, MapPin, ChevronRight } from 'lucide-react'
import TravelerTabs from '../../../components/TravelerTabs/TravelerTabs'
import { getTravelerDashboard } from '../../../services/travelerDashboardService'

export default function TravelerDashboard() {
  const navigate = useNavigate(); const [data, setData] = useState(null); const [error, setError] = useState('')
  useEffect(() => { getTravelerDashboard().then(setData).catch(e => setError(e.message)) }, [])
  if (!data) return <main className="portal-page traveler-dashboard-page"><div className="container traveler-dashboard-shell">{error ? <div className="inline-banner">{error}</div> : 'Loading your dashboard…'}</div></main>
  const trip = data.upcoming_trip
  return <main className="portal-page traveler-dashboard-page"><div className="container traveler-dashboard-shell">
    <header className="traveler-app-bar"><div className="traveler-app-bar-brand"><div className="traveler-app-bar-logo">GV</div><div><h1>Welcome back, {data.user.first_name}</h1><p>Your next trip is waiting</p></div></div><div className="traveler-avatar-pill">{data.user.first_name?.[0]}</div></header>
    <section className="traveler-card traveler-countdown-card">{trip ? <div className="traveler-countdown-content" onClick={() => navigate(`/app/traveler/trips/${trip.id}`)}><div className="traveler-countdown-left"><div className="traveler-countdown-icon"><Clock size={20} /></div><div><p className="eyebrow">Upcoming trip</p><h2>{trip.title}</h2><p>{new Date(trip.start_time).toLocaleString()} · {trip.business_name || `${trip.first_name} ${trip.last_name}`}</p></div></div><button className="btn btn-outline btn-sm traveler-countdown-btn" onClick={event => { event.stopPropagation(); navigate(`/app/traveler/messages${trip.conversation_id ? `?conversation=${trip.conversation_id}` : ''}`) }}><MessageCircle size={16} /> Message guide</button></div> : <div className="traveler-empty-card"><div><p className="eyebrow">No trips booked yet</p><h2>Let’s find your next escape</h2></div><button className="btn btn-primary" onClick={() => navigate('/search')}>Explore now</button></div>}</section>
    {data.custom_requests?.length > 0 && <section className="traveler-section traveler-bids-section"><div className="traveler-section-header"><div><p className="eyebrow">Action required</p><h2>Your custom trip proposals</h2><span>Compare provider ideas and refine the plan before booking.</span></div><button className="text-link" onClick={() => navigate('/app/traveler/requests')}>View all <ChevronRight size={16} /></button></div><div className="traveler-custom-bids-grid">{data.custom_requests.map(request => <button key={request.id} className="traveler-custom-bid-card" onClick={() => navigate(`/app/traveler/requests?request=${request.id}`)}><div><strong>{request.title}</strong><span><MapPin size={14} /> {request.destination_name}</span><small>{request.proposal_count} provider proposal{Number(request.proposal_count) === 1 ? '' : 's'} · {request.unread_message_count || 0} unread repl{Number(request.unread_message_count) === 1 ? 'y' : 'ies'}</small></div><div className="traveler-custom-bid-action"><span className="traveler-bid-status">{request.status}</span><ChevronRight size={19} /></div></button>)}</div></section>}
    <section className="traveler-section"><div className="traveler-section-header"><div><p className="eyebrow">Curated picks</p><h2>Recommended for you</h2></div><button className="text-link" onClick={() => navigate('/search')}>See all <ChevronRight size={16} /></button></div><div className="traveler-recommendations-grid">{data.recommendations.map(item => <article key={item.id} className="traveler-rec-card" onClick={() => navigate(`/experience/${item.slug}`)}>{item.image ? <img src={item.image} alt={item.title} /> : <div className="search-image-placeholder">GuideVerse</div>}<div className="traveler-rec-body"><h3>{item.title}</h3><p><MapPin size={14} />{item.location}</p><div className="traveler-rec-footer"><span>{item.currency} {Number(item.price).toFixed(2)}/person</span><div className="traveler-rating-pill"><Sparkles size={13} />{item.rating}</div></div></div></article>)}</div></section>
    <section className="traveler-section"><div className="traveler-section-header"><div><p className="eyebrow">Quick actions</p><h2>Start something new</h2></div></div><div className="traveler-quick-actions"><button className="traveler-action-card" onClick={() => navigate('/app/traveler/requests')}><Sparkles size={18} /><span>Post Custom Request</span></button><button className="traveler-action-card" onClick={() => navigate('/app/traveler/ai-planner')}><Zap size={18} /><span>Launch AI Planner</span></button><button className="traveler-action-card" onClick={() => navigate(`/search${data.nearby_query ? `?q=${encodeURIComponent(data.nearby_query)}` : ''}`)}><Compass size={18} /><span>Find Instant Nearby</span></button></div></section>
  </div><TravelerTabs /></main>
}
