import { useEffect, useState } from 'react'
import { Send } from 'lucide-react'
import TravelerTabs from '../../../components/TravelerTabs/TravelerTabs'
import { getTravelerConversations, sendTravelerMessage } from '../../../services/travelerPortalService'

export default function TravelerMessages() {
  const requested = new URLSearchParams(window.location.search).get('conversation')
  const [conversations, setConversations] = useState([]); const [selected, setSelected] = useState(null); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [sending, setSending] = useState(false)
  useEffect(() => { getTravelerConversations().then(items => { setConversations(items); setSelected(items.find(item => item.id === requested) || items[0] || null) }).catch(e => setError(e.message)).finally(() => setLoading(false)) }, [requested])
  const send = async () => { const body = message.trim(); if (!body || !selected) return; setSending(true); try { const saved = await sendTravelerMessage(selected.id, body); setConversations(items => items.map(item => item.id === selected.id ? { ...item, messages: [...item.messages, saved] } : item)); setSelected(item => ({ ...item, messages: [...item.messages, saved] })); setMessage('') } catch (e) { setError(e.message) } finally { setSending(false) } }
  if (loading) return <main className="portal-page"><div className="container">Loading conversations…</div><TravelerTabs /></main>
  return <main className="portal-page" style={{ paddingBottom: 72 }}><div className="split-pane" style={{ minHeight: 'calc(100dvh - 140px)' }}><aside style={{ borderRight: '1px solid var(--color-border)', background: 'var(--color-surface)' }}><h2 style={{ padding: 'var(--space-4)', borderBottom: '1px solid var(--color-border)' }}>Conversations</h2>{conversations.map(item => <button key={item.id} onClick={() => setSelected(item)} style={{ width: '100%', textAlign: 'left', padding: 'var(--space-3) var(--space-4)', borderBottom: '1px solid var(--color-border)', background: selected?.id === item.id ? 'var(--color-surface-raised)' : 'transparent' }}><strong>{item.business_name || `${item.first_name} ${item.last_name}`}</strong><div style={{ fontSize: 'var(--text-xs)' }}>{item.subject}</div></button>)}</aside><section style={{ display: 'flex', flexDirection: 'column' }}>{error && <div className="inline-banner">{error}</div>}{!selected ? <div className="settings-empty"><strong>No conversations yet</strong><p>A conversation is created when a booking is confirmed.</p></div> : <><header style={{ padding: 'var(--space-4)', borderBottom: '1px solid var(--color-border)' }}><strong>{selected.business_name || `${selected.first_name} ${selected.last_name}`}</strong><span style={{ marginLeft: 8 }}>{selected.subject}</span></header><div style={{ flex: 1, padding: 'var(--space-4)', overflowY: 'auto' }}>{selected.messages.map(item => <div key={item.id} style={{ marginBottom: 'var(--space-3)', maxWidth: '75%', marginLeft: item.self ? 'auto' : 0, padding: 'var(--space-3)', borderRadius: 'var(--radius-control)', background: item.self ? 'var(--color-primary)' : 'var(--color-surface-raised)', color: item.self ? '#fff' : 'inherit' }}><div>{item.body}</div><small style={{display: 'block', fontSize: '0.75rem', marginTop: '4px', opacity: 0.8}}>{item.self ? 'You' : (selected.business_name || `${selected.first_name} ${selected.last_name}`)}</small></div>)}</div><div style={{ display: 'flex', gap: 8, padding: 'var(--space-4)', borderTop: '1px solid var(--color-border)' }}><input className="input-field" value={message} onChange={event => setMessage(event.target.value)} onKeyDown={event => { if (event.key === 'Enter') send() }} placeholder="Type a message…" /><button className="btn btn-primary btn-icon" disabled={!message.trim() || sending} onClick={send}><Send size={18} /></button></div></>}</section></div><TravelerTabs /></main>
}
