import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { Edit3, Eye, LoaderCircle, Plus, Trash2 } from 'lucide-react'
import ProviderSidebar from '../../../components/ProviderSidebar/ProviderSidebar'
import { deleteExperience, listProviderExperiences } from '../../../services/providerExperienceService'

export default function ProviderListings() {
  const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [deleting, setDeleting] = useState('')
  const load = () => { setLoading(true); listProviderExperiences().then(setItems).catch(error => setError(error.message)).finally(() => setLoading(false)) }
  useEffect(load, [])
  const remove = async item => { if (!window.confirm(`Delete “${item.title}”? This cannot be undone.`)) return; setDeleting(item.id); setError(''); try { await deleteExperience(item.id); setItems(current => current.filter(entry => entry.id !== item.id)) } catch (error) { setError(error.message) } finally { setDeleting('') } }
  return <div className="portal-page provider-layout listings-page"><ProviderSidebar /><main className="provider-listings-main"><header className="provider-listings-header"><div><p className="settings-eyebrow">Provider catalog</p><h1>Your experiences</h1><span>Create, edit, preview, or remove your listings.</span></div><Link className="btn btn-primary" to="/app/provider/listings/new"><Plus size={17} /> New experience</Link></header>{error && <div className="inline-banner">{error}</div>}{loading ? <div className="provider-listings-empty"><LoaderCircle className="spinner" /> Loading listings…</div> : items.length === 0 ? <div className="provider-listings-empty"><h2>No experiences yet</h2><p>Create your first listing and publish it to travelers.</p><Link className="btn btn-primary" to="/app/provider/listings/new">Create experience</Link></div> : <div className="provider-listings-grid">{items.map(item => <article className="provider-experience-card" key={item.id}>{item.image_url ? <img src={item.image_url} alt="" /> : <div className="provider-listing-placeholder">GuideVerse</div>}<div className="provider-experience-copy"><div className="provider-listing-status"><span className={item.is_published ? 'published' : 'draft'}>{item.is_published ? 'Published' : 'Draft'}</span><small>{new Date(item.updated_at).toLocaleDateString()}</small></div><h2>{item.title}</h2><p>{item.currency} {Number(item.base_price).toFixed(2)} · Up to {item.max_capacity} guests</p><div className="provider-listing-buttons">{item.is_published && <Link className="btn btn-ghost btn-sm" to={`/experience/${item.slug}`}><Eye size={15} /> Preview</Link>}<Link className="btn btn-outline btn-sm" to={`/app/provider/listings/${item.id}/edit`}><Edit3 size={15} /> Edit</Link><button className="btn btn-ghost btn-sm listing-delete" disabled={deleting === item.id} onClick={() => remove(item)}>{deleting === item.id ? <LoaderCircle size={15} className="spinner" /> : <Trash2 size={15} />} Delete</button></div></div></article>)}</div>}</main></div>
}
