import { useEffect, useState } from 'react'
import { Check, LoaderCircle, MapPin, Pencil, Plus, Settings, Trash2, X } from 'lucide-react'
import { getPlatformConfig, updatePlatformConfig } from '../../../services/adminConfigService'
import { createAdminTourLocation, deleteAdminTourLocation, getAdminTourLocations, updateAdminTourLocation } from '../../../services/tourLocationService'

export default function PlatformConfig() {
  const [fee, setFee] = useState('')
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState('')
  const [saved, setSaved] = useState(false)
  const [locations, setLocations] = useState([])
  const [locationName, setLocationName] = useState('')
  const [editingLocation, setEditingLocation] = useState(null)
  const [locationLoading, setLocationLoading] = useState(true)
  const [locationSaving, setLocationSaving] = useState(false)
  const [locationError, setLocationError] = useState('')
  useEffect(() => { getPlatformConfig().then(data => setFee(String(data.service_fee_percent))).catch(e => setError(e.message)).finally(() => setLoading(false)); getAdminTourLocations().then(setLocations).catch(e => setLocationError(e.message)).finally(() => setLocationLoading(false)) }, [])
  const submit = async event => { event.preventDefault(); setSaving(true); setError(''); setSaved(false); try { const data = await updatePlatformConfig(Number(fee)); setFee(String(data.service_fee_percent)); setSaved(true) } catch (e) { setError(e.message) } finally { setSaving(false) } }
  const saveLocation = async event => { event.preventDefault(); setLocationSaving(true); setLocationError(''); try { const location = editingLocation ? await updateAdminTourLocation(editingLocation.id, locationName) : await createAdminTourLocation(locationName); setLocations(current => editingLocation ? current.map(item => item.id === location.id ? location : item) : [...current, location]); setLocationName(''); setEditingLocation(null) } catch (e) { setLocationError(e.message) } finally { setLocationSaving(false) } }
  const removeLocation = async location => { if (!window.confirm(`Delete ${location.name}?`)) return; setLocationError(''); try { await deleteAdminTourLocation(location.id); setLocations(current => current.filter(item => item.id !== location.id)) } catch (e) { setLocationError(e.message) } }
  const editLocation = location => { setEditingLocation(location); setLocationName(location.name); setLocationError('') }
  return <main className="portal-page admin-layout container"><header className="portal-header"><div><p className="settings-eyebrow">Admin Portal</p><h1>Platform Config</h1><p>Manage global marketplace pricing and operational settings.</p></div><Settings size={30} /></header>{error && <div className="inline-banner">{error}</div>}{saved && <div className="inline-banner success"><Check size={16} /> Platform configuration saved</div>}{loading ? <div className="portal-card settings-section"><LoaderCircle className="spinner" /> Loading configuration…</div> : <form className="portal-card settings-section" onSubmit={submit}><div className="settings-section-heading"><div><p className="settings-eyebrow">Marketplace fees</p><h2>Traveler service fee</h2><span>Applied to every database-generated checkout quote and payment.</span></div></div><label className="input-group"><span className="input-label">Service fee percentage</span><div className="platform-fee-input"><input className="input-field" type="number" min="0" max="100" step="0.01" value={fee} onChange={event => setFee(event.target.value)} required /><strong>%</strong></div><small>Example: enter 4 for a 4% traveler service fee.</small></label><div className="settings-actions"><button className="btn btn-primary" disabled={saving}>{saving ? <><LoaderCircle size={16} className="spinner" /> Saving…</> : 'Save service fee'}</button></div></form>}{locationError && <div className="inline-banner">{locationError}</div>}<section className="portal-card settings-section tour-location-settings"><div className="settings-section-heading"><div><p className="settings-eyebrow">Traveler suggestions</p><h2><MapPin size={20} /> Tour locations</h2><span>Manage the places shown as suggestions when travelers create a custom tour request.</span></div></div><form className="tour-location-form" onSubmit={saveLocation}><input className="input-field" value={locationName} onChange={event => setLocationName(event.target.value)} placeholder="e.g. Queenstown, New Zealand" required /><button className="btn btn-primary" disabled={locationSaving}>{locationSaving ? <LoaderCircle size={16} className="spinner" /> : editingLocation ? <Check size={16} /> : <Plus size={16} />}{editingLocation ? 'Save location' : 'Add location'}</button>{editingLocation && <button type="button" className="btn btn-outline" onClick={() => { setEditingLocation(null); setLocationName('') }}><X size={16} /> Cancel</button>}</form>{locationLoading ? <LoaderCircle className="spinner" /> : <div className="tour-location-list">{locations.map(location => <div className="tour-location-row" key={location.id}><span>{location.name}</span><div><button className="btn btn-outline btn-sm" onClick={() => editLocation(location)}><Pencil size={14} /> Edit</button><button className="btn btn-danger btn-sm" onClick={() => removeLocation(location)}><Trash2 size={14} /> Delete</button></div></div>)}</div>}</section></main>
}
